# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateUseWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateUserWindow(object):
    def setupUi(self, CreateUserWindow):
        CreateUserWindow.setObjectName("CreateUserWindow")
        CreateUserWindow.resize(641, 340)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(CreateUserWindow)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 611, 321))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.l_surname = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.l_surname.setObjectName("l_surname")
        self.horizontalLayout.addWidget(self.l_surname)
        self.le_surname = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.le_surname.setObjectName("le_surname")
        self.horizontalLayout.addWidget(self.le_surname)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.l_name = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.l_name.setObjectName("l_name")
        self.horizontalLayout_3.addWidget(self.l_name)
        self.le_name = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.le_name.setObjectName("le_name")
        self.horizontalLayout_3.addWidget(self.le_name)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.l_patronymic = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.l_patronymic.setObjectName("l_patronymic")
        self.horizontalLayout_2.addWidget(self.l_patronymic)
        self.le_patronimyc = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.le_patronimyc.setObjectName("le_patronimyc")
        self.horizontalLayout_2.addWidget(self.le_patronimyc)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pB_load_fingerprint = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pB_load_fingerprint.setObjectName("pB_load_fingerprint")
        self.verticalLayout_4.addWidget(self.pB_load_fingerprint)
        self.l_fingerprint_path = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.l_fingerprint_path.setObjectName("l_fingerprint_path")
        self.verticalLayout_4.addWidget(self.l_fingerprint_path)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pB_load_photo = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pB_load_photo.setObjectName("pB_load_photo")
        self.verticalLayout_5.addWidget(self.pB_load_photo)
        self.l_image_path = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.l_image_path.setObjectName("l_image_path")
        self.verticalLayout_5.addWidget(self.l_image_path)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.pb_create = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pb_create.setObjectName("pb_create")
        self.horizontalLayout_5.addWidget(self.pb_create)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 2)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.setStretch(3, 1)

        self.retranslateUi(CreateUserWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateUserWindow)

    def retranslateUi(self, CreateUserWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateUserWindow.setWindowTitle(_translate("CreateUserWindow", "Добавить пользователя"))
        self.l_surname.setText(_translate("CreateUserWindow", "Фамилия"))
        self.l_name.setText(_translate("CreateUserWindow", "Имя"))
        self.l_patronymic.setText(_translate("CreateUserWindow", "Отчество"))
        self.pB_load_fingerprint.setText(_translate("CreateUserWindow", "Загрузить отпечаток"))
        self.l_fingerprint_path.setText(_translate("CreateUserWindow", "Отпечаток"))
        self.pB_load_photo.setText(_translate("CreateUserWindow", "Загрузить фотографию"))
        self.l_image_path.setText(_translate("CreateUserWindow", "Фотография"))
        self.pb_create.setText(_translate("CreateUserWindow", "Создать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateUserWindow = QtWidgets.QWidget()
    ui = Ui_CreateUserWindow()
    ui.setupUi(CreateUserWindow)
    CreateUserWindow.show()
    sys.exit(app.exec_())
